name: Create new modeling round

on:
  push:
    paths:
      - auxiliary-data/modeled-clades/*.txt
      - .github/workflows/create-modeling-round.yaml
  workflow_dispatch:

permissions:
    contents: write
    pull-requests: write

jobs:
  create-modeling-round:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v4

      - name: Install uv ðŸŒˆ
        uses: astral-sh/setup-uv@v2
        with:
          version: "0.4.9"

      - name: Set up Python ðŸ
        uses: actions/setup-python@v5
        with:
            python-version-file: "src/.python-version"

      - name: Create clade list ðŸ¦ 
        run: |
          uv run src/get_clades_to_model.py

      - name: Add new round to hub tasks.json ðŸ“
        run: |
          echo "Not implemented yet"

      - name: Get current date and time ðŸ•°ï¸
        run: |
          PR_DATETIME=$(date +'%Y-%m-%d_%H-%M-%S')
          echo "PR_DATETIME=$PR_DATETIME" >> $GITHUB_ENV

      - name: Create PR for new modeling round ðŸš€
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $PR_DATETIME
          git checkout -b new_round_"$PR_DATETIME"
          git push -u origin new_round_"$PR_DATETIME"
          gh pr create \
            --base main \
            --title "Add new round $PR_DATETIME" \
            --body "This PR was created via GitHub Actions: generate clade list and new round config."
