name: Create ensemble

on:
  schedule:
    - cron: "0 01 * * 4" # every Thursday at 1 AM UTC (8-9 Wednesday Eastern)
  workflow_dispatch:

permissions:
    contents: write
    pull-requests: write

jobs:
  create-clade-modeling-round:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v5
        with:
            # don't check out repo folders with large amounts of data
            # (e.g., model-output, target-data)
            sparse-checkout: |
              model-output/Hub-ensemble/
              src/

      - name: Set up R ðŸ“Š
        uses: r-lib/actions/setup-r@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590  #v2.11.4
        with:
          r-version: 4.4.1
          install-r: true
          use-public-rspm: true
          extra-repositories: 'https://hubverse-org.r-universe.dev'

      - name: Set up renv ðŸ“¦
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        uses: r-lib/actions/setup-renv@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590  #v2.11.4
        with:
          working-directory: src

      - name: Create ensemble model ðŸ¦ 
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          Rscript ensemble_model.R
        working-directory: src

      - name: Get current date and time ðŸ•°ï¸
        run: |
          PR_DATETIME=$(date +'%Y-%m-%d_%H-%M-%S')
          echo "PR_DATETIME=$PR_DATETIME" >> $GITHUB_ENV

      - name: Create PR for ensemble model ðŸš€
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b ensemble_"$PR_DATETIME"
          git add model-output/Hub-ensemble/
          git commit -m "Add ensemble $PR_DATETIME"
          git push -u origin ensemble_"$PR_DATETIME"
          gh pr create \
            --base main \
            --title "Add ensemble model $PR_DATETIME" \
            --body "This PR was created via GitHub Actions: create-ensemble.json."
