name: Create new modeling round

on:
  push:
    paths:
      - auxiliary-data/modeled-clades/*.txt
      - .github/workflows/create-modeling-round.yaml
  workflow_dispatch:

permissions:
    contents: write
    pull-requests: write

jobs:
  create-modeling-round:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Install uv ğŸŒˆ
        uses: astral-sh/setup-uv@v2
        with:
          version: "0.4.9"

      - name: Set up Python ğŸ
        uses: actions/setup-python@v5
        with:
            python-version-file: "src/.python-version"

      - name: Create clade list ğŸ¦ 
        run: |
          uv run src/get_clades_to_model.py

      - name: Add new round to hub tasks.json ğŸ“
        run: |
          echo "Not implemented yet"

      - name: Create PR for new modeling round ğŸš€
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b new_round_$(date +%Y-%m-%d-%H%M%S)
          git push -u origin new_round_$(date +%Y-%m-%d-%H%M%S)
          gh pr create \
            --base main \
            --title "Add new round $(date +%Y-%m-%d-%H%M%S)" \
            --body "This PR was created via GitHub Actions: generate clade list and new round config."

